name: CI
on:
  pull_request:
  push: {branches: [main]}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: ${{ matrix.python }}}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Lint & static type check
        run: |
          ruff check src tests
          mypy src/my_agent_project -p agentic_tools
      - name: Tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: pytest -q
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
