name: Create Codespaces prebuild
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  prebuild:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository }}/codespace:latest
          cacheFrom: ghcr.io/${{ github.repository }}/codespace:latest
          push: always

