name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run tests
        run: |
          mkdir -p tests/.reports
          pytest
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports
          path: tests/.reports/
