name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-cov==5.*
      - name: Run tests
        run: pytest --cov=src --cov-report=xml -q
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.xml
