name: CI

on:
  push:
    branches: [main, bicycle, scooter, dev]
  pull_request:
    branches: [main, bicycle, scooter]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
        hatch env create
        
    - name: Run ruff
      run: hatch run lint:ruff check
      
    - name: Run mypy
      run: hatch run lint:mypy
      
    - name: Run tests
      run: hatch run test:pytest --cov=src --cov-report=xml
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
